### ISSUE TITLE
Wrong date on Restart Program Tab

### ISSUE THREAD

**Issue by ueltonVeslei** [AdobeDocs/certification.pt-BR#1]
Issue in ./help/certifications/faq.md

"The Restart Program ended on October 20, 2023. It was a one-time offering that will not be repeated in the future."

![image](https://github.com/AdobeDocs/certification.pt-BR/assets/15862400/ec607c77-baed-4958-a412-f162f6a7cde4)

**Comment by KristynaVitekerova** [comment]
@ueltonVeslei Thank you for your feedback. This is being reviewed and tracked in G11N-15508.

**Comment by pagrochowskiJON** [comment]
@ueltonVeslei: it seems everything is okay, could you clarify the issue, please?

**Comment by ueltonVeslei** [comment]
> @ueltonVeslei: it seems everything is okay, could you clarify the issue, please?

I imagined that the end date of the Adobe Restart program was incorrect because it was still possible to carry out renewals.

**Comment by jonsamhudec** [comment]
Thank you very much!
Two programs were available for certificate renewal. Firstly, the Renewal Program, which mandates renewing the Adobe certification every two years. Failure to renew prior to expiration necessitates retaking the full certification exam for recertification.
Secondly, the Restart Program, which concluded on October 20, 2023. Regrettably, this program has since ended.
